version: "3.9"

services:
  app:
    image: karel95/express-app:latest
    ports:
      - "3000:3000"
    container_name: express-app
    restart: unless-stopped

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=60
    restart: unless-stopped
